version: "3"
services:
  web:
    image: nginx:alpine
    container_name: flarum-web
    volumes:
      - ./:/var/www
      - ./nginx/flarum.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx.conf:/etc/nginx/conf.d/.nginx.conf
    ports:
    - 8080:80
    networks:
      - code-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: flarum-fpm.dockerfile
    image: flarum-fpm:1
    container_name: flarum-php
    volumes:
      - ./:/var/www
    networks: 
      - code-network
      - db-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    # container_name: flarum-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks: 
      - db-network

networks:
    code-network:
        driver: bridge
        name: web
        external: true
    db-network:
      driver: bridge

volumes:
  db: